export const UI_COPY = Object.freeze({
  loading: Object.freeze({
    title: "正在查询列车数据…",
    stage: "正在连接数据源",
    recognized: "已识别",
    preserve: "可停止生成，已返回内容会保留",
    followupPlaceholder: "继续追问…",
  }),
  schedule: Object.freeze({
    columns: Object.freeze(["车站", "到达", "出发"]),
    missingTime: "--",
    note: "以下为图定计划时刻，不代表当天实际运行时刻或正晚点状态。",
    source: "列车时刻",
    details: "查询详情",
    sampleData: "示例数据",
  }),
  routing: Object.freeze({
    title: "车组交路",
    label: "交路记录",
    columns: Object.freeze(["车次", "记录时间"]),
    timeSemantics: "以下为记录时间，不是列车到发时间。",
    integrityNote: "记录可能不完整，以实际运行情况为准。",
    source: "交路记录",
    batchPrefix: "查询这",
    batchSuffix: "趟车的时刻表",
  }),
  batch: Object.freeze({
    title: "时刻查询",
    returned: "已返回",
    found: "已查到",
    pending: "暂未返回",
    retry: "仅重试",
    retained: "保留已查到的结果",
  }),
  empty: Object.freeze({
    title: "未找到当天交路记录",
    message: "暂无记录，不能据此判断停运。",
    changeDate: "更换日期",
    recent: "查看最近记录",
    historyNote: "历史记录将单独标注日期",
  }),
  error: Object.freeze({
    title: "查询服务暂时异常",
    message: "你的提问已保留，可稍后重试。",
    retry: "重试",
    settings: "检查模型设置",
    details: "错误详情",
    keyLabel: "API Key",
    invalidKey: "密钥无效，请检查后重试",
  }),
  details: Object.freeze({
    source: "来源",
    sample: "示例数据",
    date: "数据日期",
    timeBasis: "时间口径",
    latency: "查询耗时",
    usage: "用量",
    technicalLog: "查看技术日志",
  }),
  reading: Object.freeze({
    bottomCue: "有新内容 · 回到底部",
    guidance: "上滑阅读时暂停自动滚动；点选追问先填入输入框",
    availability: "查余票",
    changeDate: "换个日期",
  }),
  history: Object.freeze({
    title: "对话历史",
    search: "搜索对话…",
    create: "新建对话",
    today: "今天",
    yesterday: "昨天",
    earlier: "更早",
    operations: "对话操作",
    rename: "重命名",
    delete: "删除对话",
    cancel: "取消",
    noMatches: "没有匹配的对话",
    settings: "模型与设置",
    help: "使用帮助",
  }),
});
